"""altering name and enabled is not nullable

Revision ID: 2c1b0b331f08
Revises: 3b59497e4b11
Create Date: 2026-01-30 17:06:39.548074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c1b0b331f08'
down_revision: Union[str, Sequence[str], None] = '3b59497e4b11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('feature_flags', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('feature_flags', 'enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('feature_flags', 'enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('feature_flags', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
