"""adding created_at to flag_table

Revision ID: 3b59497e4b11
Revises: 717a64361055
Create Date: 2026-01-30 16:21:57.887207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b59497e4b11'
down_revision: Union[str, Sequence[str], None] = '717a64361055'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feature_flags', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feature_flags', 'created_at')
    # ### end Alembic commands ###
